### ISSUE TITLE
Add tags to project table

### ISSUE THREAD

**Issue by ishaaa-ai** [itsninaricci29/CONNECTeD#65] opened 2020-03-04 22:37 UTC
Modify front end as well to make sure tags are being added to the ProjectTags table so that projects can be connected to Tags. 

Implementation:
We should use the same endpoint that we have for creating projects and just update it to create the project and the corresponding entry in ProjectTags table.

We can use the API for create users and saving their tags as a guideline.

**Comment by VeerpalBrar** [comment] 2020-03-05 15:38
This looks like a duplicate of https://github.com/itsninaricci29/CONNECTeD/issues/46 . Let's code one issue and keep the other one open.

**Comment by ishaaa-ai** [comment] 2020-03-07 17:24
Sorry, didn't realize there was someone already assigned to this issue.

**Closed** 2020-03-16 13:39 UTC
Labels: projects, tags
